{% set name = "nbfinder" %}
{% set version = "1.0.2" %}
{% set sha256 = "3cc9e43e08e1d9ec83040fac6bbf19a31d790327b045cd9d4e07648f7616356e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - ipython
    - nbformat

  run:
    - python >={{ python_min }}
    - ipython
    - nbformat

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbfinder

about:
  home: https://github.com/hadim/nbfinder
  license: MIT
  license_file: LICENSE
  summary: 'Importing Jupyter Notebooks as Modules'
  license_family: MIT
  dev_url: https://github.com/hadim/nbfinder
  doc_url: https://github.com/hadim/nbfinder

extra:
  recipe-maintainers:
    - hadim
