travis:
  secure:
    BINSTAR_TOKEN: BNiRV6l7MVexxhWjeoj7yMFg/Uz8nwZUp8ovBj4TTAAEKultaxXd/kZQj3T4ATmnKq54qe2r07+uuOyvE8Gw5b+wsqSVD+BnHMarEvtv6f+JZnd3vmfXZqtcV2sAH5vEYQS8Y+JPOyU32mmSDXol+nJlhg8wmBWPPZQqMPgp4djyGoW/t1FjFNEU8DEU+DoPFry9bQzYCookAOho28q6SXRSTFRxVr5WevJ4HzdwwxI/b/t9OxH+FrptrIrLdtC429TcFKQ54StwzXXgWcCFHk+E21heMvFXRE3/zpaQjmHy4Vp6Hb5+eLia9y2tTLiDu0JiWUbJ4X4NkfJK26ydILt0RdyXS88/251oAqlaIHl8FsSCr9iFiBVTxCqjZUJ+yl61gfvPCNqMmWgBb7NEFjCjkGdkcZR7zSgpPTtkIPTnOfFiSK2Yy3bowUCyvSqPg6xogDbWMRq2o3JEKDLmgPSgKhGDClR151hoLz7VP6RIox4u6QQWp0vt21hpv30rvSGYiApNQYXwQ41MUGuC3MAhrtzqacgSUkgxSiN9AvQZ0YKdPLgfInpdkfsuljz5B2NZ0YPeMyK/PdsmPWJ1s+COVwMAdIO9yL4IYfOwvZseW77xUVhFv8otIbWnbK5s6Lzl3uSrkRp3EZq14NBpdhWS+dIfmLBSedyMaSPV4Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
