travis:
  secure:
    BINSTAR_TOKEN: nDOE5JuyYDTcrVtBaWi9Msx6G0139wZyuzYFeGdBzxPrYQoemzzgmjnUec3gWDqr6l307O7a8K0+A2xUK/mgfX6PCNmjesJqYpAVmSq9os/CW4G40BLNeAvsCzQD2ZzGC//5k7bCVd+oOncWxcneHNgAP2IXK6kPjeBGJs3LdIfSokNHG/zu/m8nHGe3VHvyqOcbKo3AONcqbsXCP8hY6YNqkN/YYb1aPRE40Ri3AUiI9uH4wpRH1UAFoA/nnn/4Qcazzntg7nBzA8wR2x+SPG8uy8BL1WKa0AbRf/Mt8QKdnT9ZWf1fAnJR2v8Stq+cZ/cdXEQQCnapezIs4qY3zju90/camg5u6vyMPGYZrdO5E9dEDtqSmCnvEXmYA3qvFFFllFunSBqqXXaATzbnb2DQCAwydS5VWFYI3rxZ5o3Jv4MolL8lipvQpTBK26D3EdjbmMGQyYIX0wJ4ucRdltF7HZdBZKhYS/72X6jAJw9AoUqbNHyRKSnXi4MdrX8TS4Rgn6mk3BHEcSCau3CPgp6FpIBFmvOzvq7idVGihREwaw0GFmInL18Rt3uGwOkUY2GoRL1aIM/RWjwXNOQtkj5Og72OsyWyfmfaYRkEFmfLN4ocgbsuZcO4mDrxXkjbMd9MVCvh8hpmOPMS127HNsbg3X+2DYLtrUP43epP6yo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
